"""initial version

Revision ID: 4d0238d04c7e
Revises: 
Create Date: 2019-09-07 12:04:52.706665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d0238d04c7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('category', sa.Enum('SAILPLANE', 'PLANE', 'ULTRALIGHT', 'HELICOPTER', 'DRONE', 'OTHER', 'WTF', name='aircraftcategory'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_message', sa.String(length=255), nullable=False),
    sa.Column('request_timestamp', sa.DateTime(), nullable=True),
    sa.Column('respond_message', sa.String(length=255), nullable=True),
    sa.Column('respond_timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=6), nullable=False),
    sa.Column('device_type', sa.Enum('FLARM', 'ICAO', 'OGN', name='devicetype'), nullable=True),
    sa.Column('registration', sa.String(length=7), nullable=True),
    sa.Column('cn', sa.String(length=3), nullable=True),
    sa.Column('show_track', sa.Boolean(), nullable=False),
    sa.Column('show_identity', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('aircraft_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aircraft_type_id'], ['aircraft_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=9), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('antenna', sa.Enum('UNKNOWN', 'CHINESE_9DB_JPOLE', 'JETVISION_ACTIVE', 'WIMO_SPERRTOPF', 'GROUND_PLANE', 'SELF_BUILT', name='antenna'), nullable=True),
    sa.Column('preamplifier', sa.Enum('UNKNOWN', 'NONE', 'TERRA_AB010', 'TERRA_AB011', 'SELF_BUILT_WITHOUT_FILTER', 'SELF_BUILT_WITH_FILTER', name='preamplifier'), nullable=True),
    sa.Column('rx_filter', sa.Enum('UNKNOWN', 'NONE', 'SAW', 'CBP840', 'CAVITY', name='rxfilter'), nullable=True),
    sa.Column('sdr_dongle', sa.Enum('UNKNOWN', 'BLUE_PLASTIC', 'BLACK_PLASTIC', 'RTLSDR_COM', 'NOELEC', 'OTHER', name='sdrdongle'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association_table_users_devices',
    sa.Column('user__id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['user__id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user__id', 'device_id')
    )
    op.create_table('association_table_users_receivers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['receivers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'receiver_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_table_users_receivers')
    op.drop_table('association_table_users_devices')
    op.drop_table('receivers')
    op.drop_table('devices')
    op.drop_table('users')
    op.drop_table('device_claims')
    op.drop_table('aircraft_types')
    # ### end Alembic commands ###
