"""Initial version

Revision ID: 5093a30d53b7
Revises: 
Create Date: 2019-08-12 10:36:38.929451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5093a30d53b7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "receivers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("antenna", sa.String(), nullable=True),
        sa.Column("preamplifier", sa.String(), nullable=True),
        sa.Column("filter", sa.String(), nullable=True),
        sa.Column("sdr_dongle", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "association_table_users_devices",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("user_id", "device_id"),
    )
    op.create_table(
        "association_table_users_receivers",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("receivers_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["receivers_id"], ["receivers.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("user_id", "receivers_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("association_table_users_receivers")
    op.drop_table("association_table_users_devices")
    op.drop_table("receivers")
    # ### end Alembic commands ###
